### PR TITLE
Releasing 0.4.4

### PR DESCRIPTION
**Pull request by ThomasSchellenbergNextCentury**
Includes the updated version number in the _version file and the docs

### CODE REVIEW

**Review by deanwetherby — APPROVED** [review]

**Review by rartiss55 — APPROVED** [review]

**Comment by kdrumm** [comment]
I'm occasionally getting a unit test failure on test_multiple_write_different_sizes (tests.test_recorder.TestImageRecorder).  Is it just me?  Failed 2 out of 4 runs so far.

**Comment by deanwetherby** [comment]
@kdrumm  Weird that all the GH Actions unit tests passed. I'll check locally.

**Comment by ThomasSchellenbergNextCentury** [comment]
Unit tests are passing for me. I've been running them on the latest PR all morning, and I just reran them. :shrug:

**Comment by rartiss55** [comment]
Yeah passing for me too -- I tried a few times just in case.

**Comment by kdrumm** [comment]
Sounds like its localized to me and not the code.

**Pull request merged**
