### PR TITLE
MCS 1548 ghosted objects are still visible

### PR DESCRIPTION
**Pull request by jaudick**
I updated test 68 so that ball 2 was smaller and inside ball 1 for consistent behavior. Now ball 1 will block ball 2 from being seen but they still do not collide

### CODE REVIEW

**Review by phile-caci — COMMENTED** [review]
Hey @jaudick,

Tested with:
https://resources.machinecommonsense.com/eval-scenes-5/alpha_0002_09_B2_debug.json

It looks good but I wasn't sure about one thing.  When the magenta truck is partially visible, the metadata shows that visibility is false (it's true when the magenta truck is fully in view).  Is this expected?

Thanks!

**Review by ThomasSchellenbergNextCentury — APPROVED** [review]

**Comment by ThomasSchellenbergNextCentury** [comment]
@phile-caci I'm getting that the magenta truck is visible on the overlap step. Is this the same step you're looking at? I'm wondering if the RNG is giving us different results.

```
STEP: 110
ACTION: Pass
HABITUATION TRIAL: NONE
RETURN STATUS: SUCCESSFUL
REWARD: -0.11
SELF METADATA:
  CAMERA HEIGHT: 1.5
  HEAD TILT: -0.0
  POSITION: {'x': 0.0, 'y': 1.5, 'z': -4.5}
  ROTATION: 0.0
  HAPTIC FEEDBACK: {'on_lava': False}
OBJECTS: 2 TOTAL
    OBJECT ID                             SHAPE  COLORS           HELD   VISIBLE  STATE  POSITION (WORLD)          DISTANCE (WORLD)    DIRECTION (WORLD)              DIMENSIONS (WORLD)                                                                                                                                                                                              
    5dac1406-8e87-4710-8519-6c01b0938390  truck  lime, green      False  True            (0.5416,0.002185,8.75)    13.34538459777832   (0.040583,-0.112235,0.992853)  [(1.0162,0.002185,8.5127), (1.0162,0.002185,8.9873), (0.067,0.002185,8.9873), (0.067,0.002185,8.5127), (1.0162,0.680185,8.5127), (1.0162,0.680185,8.9873), (0.067,0.680185,8.9873), (0.067,0.680185,8.5127)]    
    d473c33f-07eb-4b9d-bed2-d2765a56cc04  truck  magenta, purple  False  True            (0.527891,-0.0,8.749369)  13.344453811645508  (0.039559,-0.112406,0.992875)  [(1.002645,-0.0,8.512378), (1.002336,-0.0,8.986978), (0.053136,-0.0,8.98636), (0.053446,-0.0,8.51176), (1.002645,0.678,8.512378), (1.002336,0.678,8.986978), (0.053136,0.678,8.98636), (0.053446,0.678,8.51176)]
```

I think this is what @jaudick implied when he shrank the ball in test 068 in order to produce consistent behavior. On the step the two objects overlap, if the objects are the same size, then one might obstruct the other, or not, depending on Unity's RNG. IMO this makes sense -- or, rather, since it's an implausible event, the behavior is intentionally nonsensical, and the TA1 teams should expect the unexpected (if you know what I mean :smile: ). As long as the magenta truck has the correct visibility at the other steps, I believe that satisfies this ticket.

**Comment by phile-caci** [comment]
Hey @ThomasSchellenbergNextCentury ,

Sry, it's when the magenta truck starts to appear in the viewport from the left.  It doesn't show as visible until the magenta truck is fully within the viewport. It's the same as it starts to go out of the viewport (metadata has false for visible when it's partially still in view). Didn't know if that mattered or is working as expected.

> @phile-caci I'm getting that the magenta truck is visible on the overlap step. Is this the same step you're looking at? I'm wondering if the RNG is giving us different results.
> 
> ```
> STEP: 110
> ACTION: Pass
> HABITUATION TRIAL: NONE
> RETURN STATUS: SUCCESSFUL
> REWARD: -0.11
> SELF METADATA:
>   CAMERA HEIGHT: 1.5
>   HEAD TILT: -0.0
>   POSITION: {'x': 0.0, 'y': 1.5, 'z': -4.5}
>   ROTATION: 0.0
>   HAPTIC FEEDBACK: {'on_lava': False}
> OBJECTS: 2 TOTAL
>     OBJECT ID                             SHAPE  COLORS           HELD   VISIBLE  STATE  POSITION (WORLD)          DISTANCE (WORLD)    DIRECTION (WORLD)              DIMENSIONS (WORLD)                                                                                                                                                                                              
>     5dac1406-8e87-4710-8519-6c01b0938390  truck  lime, green      False  True            (0.5416,0.002185,8.75)    13.34538459777832   (0.040583,-0.112235,0.992853)  [(1.0162,0.002185,8.5127), (1.0162,0.002185,8.9873), (0.067,0.002185,8.9873), (0.067,0.002185,8.5127), (1.0162,0.680185,8.5127), (1.0162,0.680185,8.9873), (0.067,0.680185,8.9873), (0.067,0.680185,8.5127)]    
>     d473c33f-07eb-4b9d-bed2-d2765a56cc04  truck  magenta, purple  False  True            (0.527891,-0.0,8.749369)  13.344453811645508  (0.039559,-0.112406,0.992875)  [(1.002645,-0.0,8.512378), (1.002336,-0.0,8.986978), (0.053136,-0.0,8.98636), (0.053446,-0.0,8.51176), (1.002645,0.678,8.512378), (1.002336,0.678,8.986978), (0.053136,0.678,8.98636), (0.053446,0.678,8.51176)]
> ```
> 
> I think this is what @jaudick implied when he shrank the ball in test 068 in order to produce consistent behavior. On the step the two objects overlap, if the objects are the same size, then one might obstruct the other, or not, depending on Unity's RNG. IMO this makes sense -- or, rather, since it's an implausible event, the behavior is intentionally nonsensical, and the TA1 teams should expect the unexpected (if you know what I mean 😄 ). As long as the magenta truck has the correct visibility at the other steps, I believe that satisfies this ticket.

**Comment by ThomasSchellenbergNextCentury** [comment]
@phile-caci Oh, I see it now -- good catch! That **is** weird. The magenta truck isn't marked as visible until step 93, but it's definitely visible starting on step 88. Furthermore, it becomes not-visible again on step 129, when it should instead remain visible until step 136 or 137. @jaudick Any thoughts as to why this is happening?

Here are steps 88, 93, 129, and 136.

frame_image_88

frame_image_93

frame_image_129

frame_image_136

**Comment by ThomasSchellenbergNextCentury** [comment]
@phile-caci @jaudick I'm actually seeing the issue occur in the latest release version as well, so it doesn't appear to have been caused by this ticket. I'll create another ticket to investigate it further. (Phi - to clarify - the "ghosting" object is the GREEN truck, so it's the GREEN truck's visibility that's affected by this ticket.)

**Review by brianpippin — APPROVED** [review]
Code looks good.

**Pull request merged**
