### PR TITLE
Fixed structural object count to always be 5 for grid floor removing sim obj physics script

### PR DESCRIPTION
**Pull request by jaudick**
[Unity](https://github.com/NextCenturyCorporation/ai2thor/pull/249)
The autofix appeared to reorder the oracle metadata alphabetically too so thats why some tests appear to be changed more than they are.

### CODE REVIEW

**Review by ThomasSchellenbergNextCentury — APPROVED** [review]
I'm still getting errors for tests 41 and 42 at Levels 1 and 2.

**Review by ThomasSchellenbergNextCentury — CHANGES_REQUESTED** [review]
Whoops, that Approval was supposed to be a Request Changes...

**Comment by jaudick** [comment]
@ThomasSchellenbergNextCentury Whoops for me too, forgot to fix those. Should be fixed now and if this gets approved we should probably still wait for the TA1 approval.

**Review by ThomasSchellenbergNextCentury — APPROVED** [review]

**Comment by brianpippin** [comment]
If merging the floor fix in ai2thor then this can go I think.

**Review by brianpippin — APPROVED** [review]
Think we suggested merging this so we can see some performance improvements and test for any unexpected issues.

**Comment by ThomasSchellenbergNextCentury** [comment]
@brianpippin Do we have an up-to-date list of TA1 engineering leads that we could contact first to make sure that removing the floor from the oracle output metadata won't mess up their systems?

**Comment by ThomasSchellenbergNextCentury** [comment]
I think we got TA1's approval on this, if we want to go ahead and merge it in.

**Comment by jaudick** [comment]
@rartiss55 @brianpippin @ThomasSchellenbergNextCentury This needs approval after the latest commit

**Review by rartiss55 — APPROVED** [review]

**Review by ThomasSchellenbergNextCentury — APPROVED** [review]
Tests pass

**Pull request merged**
