### PR TITLE
Picking up static containers when switched to a pickupable object throws nre exception fixed integration testing

### PR DESCRIPTION
**Pull request by jaudick**
https://github.com/NextCenturyCorporation/ai2thor/pull/148

The test is labeled 80 because I made a bunch of tests for ramp ascension that stopped at 79 that have not been merged yet

### CODE REVIEW

**Comment by kdrumm** [comment]
I'm trying to replicate the problem using the 0.4.3 build of ai2thor to compare the difference.  However, I am unable to.  Do you know exactly how to replicate?  The integration test should fail on an older build of ai2thor like 0.4.3.

**Comment by jaudick** [comment]
> I'm trying to replicate the problem using the 0.4.3 build of ai2thor to compare the difference. However, I am unable to. Do you know exactly how to replicate? The integration test should fail on an older build of ai2thor like 0.4.3.

I left this comment of the unity pull "You can still pick up the box in the old executable. It only throws the error inside the editor console. It does not interfere with any actions, it just appears as an error. I'm not sure how to test an NRE in the integration tests but I made one that sets up the scenario"

**Comment by kdrumm** [comment]
Ok, that makes more sense.  I didn't realize it was only in the editor.  If that is the case, we should probably close this PR without merge.

**Comment by rartiss55** [comment]
I'm actually leaning towards keeping the test in -- it doesn't hurt anything/nice to have confirmation that there aren't any other issues with chest_1?

**Comment by brianpippin** [comment]
I always feel like an extra test can't hurt so long as it is stable.

**Review by brianpippin — APPROVED** [review]

**Review by kdrumm — APPROVED** [review]
You guys are right.  It certainly doesn't hurt.

**Pull request merged**
