### PR TITLE
MCS-1815 MCS-1930 Webenabled Updates: Production-Ready Server and Configurable Command Line Settings

### PR DESCRIPTION
**Pull request by ThomasSchellenbergNextCentury**
- By default, use the production-ready "waitress" library (which supposedly supports Windows) to serve the webenabled flask app. Note that the version I pinned in the requirements file is simply the most recent version.
- All of the "info" logs are now at "debug" level.
- Added argparse with the following optional settings: host, port, dev (development server), debug (debug logging)
- Ensure the log level is properly passed to all scripts.

### CODE REVIEW

**Comment by NDCACI** [comment]
This branch has some merge conflicts

**Comment by ThomasSchellenbergNextCentury** [comment]
@NDCACI Conflicts are now resolved.

**Comment by NDCACI** [comment]
The file "docs/source/schema.rst" got added during the merge fix. It looks like it might got pulled in by accident. Is it supposed to be in this PR?

**Comment by ThomasSchellenbergNextCentury** [comment]
@NDCACI Nope! Hmm... Well, just ignore all the files outside the `webenabled` folder. Everything will work itself out once we merge.

**Review by NDCACI — APPROVED** [review]

**Review by rartiss55 — APPROVED** [review]

**Pull request merged**
