### PR TITLE
MCS-2010 Added an integration test to ensure the soccer ball obstructs the tool during a RotateObject.

### PR DESCRIPTION
**Pull request by ThomasSchellenbergNextCentury**
You can see the issue pretty clearly when you run this test.

Using the current build (0.7.3), it doesn't look right.
```
python integration_tests/run_tests.py --dev --test 218
```

However, if you build my branch and run the test, it looks much better: https://github.com/NextCenturyCorporation/ai2thor/pull/354
```
python integration_tests/run_tests.py --mcs_unity_build <file_path> --dev --test 218
```

### CODE REVIEW

**Review by phile-caci — APPROVED** [review]
Ran all and test 218 integration test against companion AI2Thor branch, looks good.

**Review by NDCACI — APPROVED** [review]

**Comment by ThomasSchellenbergNextCentury** [comment]
Added two more tests for ensuring that platforms and tools correctly obstruct RotateObject (please grab the latest commit from the corresponding ai2thor branch). Note that I had to update test 217 because the slightly bigger box collider caused the agent to obstruct the tool during one of the actions (but it didn't affect the integrity of the test itself).

**Comment by phile-caci** [comment]
Ran integration against new AI2Thor build.. Looks good.

**Review by rartiss55 — APPROVED** [review]
Ran each test + ran all tests at level2 + oracle against a build from the ai2thor branch, everything passed.

**Pull request merged**
