### PR TITLE
Cubes, cups, turtle pivots centered

### PR DESCRIPTION
**Pull request by jaudick**
[Private-repo](https://github.com/NextCenturyCorporation/mcs-private/pull/152)
[Unity](https://github.com/NextCenturyCorporation/ai2thor/pull/215)
The changes are position y updates on cubes because their center pivot points were changed from the bottom of the object to their actual center of mass

### CODE REVIEW

**Review by ThomasSchellenbergNextCentury — APPROVED** [review]

**Comment by rartiss55** [comment]
I noticed this is in progress of getting merged -- wondering if anyone else was getting integration test errors? Wasn't sure if I built something incorrectly or not.

**Comment by ThomasSchellenbergNextCentury** [comment]
@rartiss55 I ran the integration tests and they worked for me, but there's currently a merge conflict, which is going to cause issues. I'm trying to resolve it now.

**Comment by ThomasSchellenbergNextCentury** [comment]
@jaudick @rartiss55 I pushed an update. Worked on 095 in isolation. Running the whole suite now.

**Comment by ThomasSchellenbergNextCentury** [comment]
Everything ran fine for me. I'm going to try merging and see what happens.

**Pull request merged**
