### PR TITLE
MCS-415: Add code that calculates a reward penalty based on the number of steps

### PR DESCRIPTION
**Pull request by brianpippin**

### CODE REVIEW

**Comment by rartiss55** [comment]
Code looks good -- I did notice some flake8 warnings though if you wouldn't mind fixing those (only about 8 or so).

**Comment by brianpippin** [comment]
> Code looks good -- I did notice some flake8 warnings though if you wouldn't mind fixing those (only about 8 or so).

Is there some code we run to fix these?  It seems super tedious to have to fix these things that are 10 characters over the line limits, 79 characters is a very small number of characters as well.  Or do we manually correct these every time?

**Comment by rartiss55** [comment]
> > Code looks good -- I did notice some flake8 warnings though if you wouldn't mind fixing those (only about 8 or so).
> 
> Is there some code we run to fix these? It seems super tedious to have to fix these things that are 10 characters over the line limits, 79 characters is a very small number of characters as well. Or do we manually correct these every time?

Sometimes I have to fix stuff myself, but in vscode/settings.json for the project, its specified to run the autopep8 formatter on save, which should be catching some of this stuff as you go/fixing it for you. Not sure why it isn't working (perhaps autopep8 isn't installed or you're missing a plugin?)

**Comment by rartiss55** [comment]
Had to double check the docs but to just command line fix things, after pip installing autopep8, you could just do:
`autopep8 --in-place --aggressive --recursive <path-to-MCS>`

**Review by rartiss55 — APPROVED** [review]

**Review by deanwetherby — APPROVED** [review]

**Review by ThomasSchellenbergNextCentury — APPROVED** [review]

**Pull request merged**
