### PR TITLE
MCS-270: Transferral goal optimal path has no pickup action for goal object

### PR DESCRIPTION
**Pull request by chrislong**

### CODE REVIEW

**Comment by chrislong** [comment]
I think maybe we should make a ticket for the problem with test_IntPhysGoal__get_objects_moving_across_collisions. I don't want it to hold this fix up.

**Comment by deanwetherby** [comment]
You are correct. It is unrelated to this ticket.

**Comment by chrislong** [comment]
The "could not find path from target object to goal" is I think expected to happen sometimes, because objects could be in the way and prevent the agent from reaching the target. The test should probably do what the actual code does, which is retry with a new scene.

**Comment by chrislong** [comment]
@deanwetherby You had a comment that said "unit tests". There is a `test_TransferralGoal_ensure_pickup_action` for this ticket. Were there other tests you had in mind?

**Comment by deanwetherby** [comment]
I think I pulled my initial approval because that specific test was failing occasionally. I should have been more clear in the comment.

**Pull request merged**
