### PR TITLE
Moving scripts folder inside package folder

### PR DESCRIPTION
**Pull request by deanwetherby**

### CODE REVIEW

**Review by brianpippin — APPROVED** [review]
LGTM

**Comment by deanwetherby** [comment]
Verified that the scripts exposed through entry_points work as intended in a new/fresh virtual environment. Moved every script that relied on the runner into the package folder. I'm not sure we need them all.

Just noticed that the ini config files are not installed. They probably have to be handled with package_data if we need them.

Left sphinx docs scripts and other items in the root scripts folder.

**Comment by rartiss55** [comment]
Sounds good/run_in_human_input_mode works!

Dunno if we want to split the scripts up later, but I don't think its a big deal right now. I guess the only other thing is if we directly reference the scripts/ folder in any docs, we want to update those paths.

**Review by rartiss55 — APPROVED** [review]

**Review by brianpippin — APPROVED** [review]

**Comment by deanwetherby** [comment]
Most importantly, does cache_addressables work?

**Comment by rartiss55** [comment]
Re cache_addressables, seems like it (I deleted what was in my Application.persistentDataPath and ran that script).

**Review by ThomasSchellenbergNextCentury — APPROVED** [review]
Agreed that there are probably some scripts that don't need to be entry points, but we can worry about reorganizing them later (when we have time).

**Comment by deanwetherby** [comment]
Thanks for the prompt feedback. I'll merge as soon as GH Actions finishes with this last push.

**Pull request merged**
