### PR TITLE
Agent freezing

### PR DESCRIPTION
**Pull request by jaudick**
[Private](https://github.com/NextCenturyCorporation/mcs-private/pull/236)
[MCS](https://github.com/NextCenturyCorporation/MCS/pull/574)
[Unity](https://github.com/NextCenturyCorporation/ai2thor/pull/246)

### CODE REVIEW

**Review by ThomasSchellenbergNextCentury — CHANGES_REQUESTED** [review]
I'm getting some errors for the new oracle test (147). Maybe it's just checking some old values left from a copy/paste? The agents looked frozen to me, so I don't _think_ my build is wonky.

```
$ python integration_tests/run_tests.py --mcs_unity_build_file ~/Development/darpa/ai2thor/unity/MCS-AI2-THOR-Unity-App-v0.5.5.x86_64 --test 147 --metadata oracle --dev
========================================
HANDMADE TEST METADATA TIER: ORACLE
Found path: /home/tschellenberg/Development/darpa/ai2thor/unity/MCS-AI2-THOR-Unity-App-v0.5.5.x86_64
RUNNING SCENE: 147.agents_freezing.scene.json
Step 2 failed:
        objects agent_female rotation_y: 180 != 149
Step 3 failed:
        objects agent_female rotation_y: 180 != 119
Step 4 failed:
        objects agent_female rotation_y: 180 != 88
Step 5 failed:
        objects agent_female rotation_y: 180 != 57
Step 6 failed:
        objects agent_female rotation_y: 180 != 27
Step 7 failed:
        objects agent_female position_x: 0.8999999761581421 != 0.92
        objects agent_female position_z: 1.7999999523162842 != 1.84
        objects agent_female rotation_y: 180 != 27
Step 8 failed:
        objects agent_female distance: 5.9186692237854 != 5.99
        objects agent_female position_x: 0.8999999761581421 != 0.94
        objects agent_female position_z: 1.7999999523162842 != 1.87
        objects agent_female rotation_y: 180 != 27
        objects agent_male rotation_y: 110 != 130
        objects soccer_ball rotation_y: 20 != 40
Step 9 failed:
        objects agent_female distance: 5.9186692237854 != 6.03
        objects agent_female position_x: 0.8999999761581421 != 0.95
        objects agent_female position_z: 1.7999999523162842 != 1.91
        objects agent_female rotation_y: 180 != 27
        objects agent_male rotation_y: 110 != 150
        objects soccer_ball rotation_y: 20 != 60
Step 10 failed:
        objects agent_female distance: 5.9186692237854 != 6.07
        objects agent_female position_x: 0.8999999761581421 != 0.97
        objects agent_female position_z: 1.7999999523162842 != 1.94
        objects agent_female rotation_y: 180 != 27
        objects agent_male rotation_y: 110 != 180
        objects soccer_ball rotation_y: 20 != 90
Step 11 failed:
        objects agent_female distance: 5.9186692237854 != 6.13
        objects agent_female position_x: 0.8999999761581421 != 1.0
        objects agent_female position_z: 1.7999999523162842 != 2.0
        objects agent_female rotation_y: 180 != 27
        objects agent_male position_z: 0.5 != 0.46
        objects agent_male rotation_y: 110 != 180
        objects soccer_ball position_z: 0.5 != 0.46
        objects soccer_ball rotation_y: 20 != 90
Step 12 failed:
        objects agent_female distance: 5.9186692237854 != 6.13
        objects agent_female position_x: 0.8999999761581421 != 1.0
        objects agent_female position_z: 1.7999999523162842 != 2.0
        objects agent_female rotation_y: 180 != 57
        objects agent_male distance: 4.564060211181641 != 4.49
        objects agent_male position_z: 0.5 != 0.42
        objects agent_male rotation_y: 110 != 180
        objects soccer_ball distance: 4.564060211181641 != 4.49
        objects soccer_ball position_z: 0.5 != 0.42
        objects soccer_ball rotation_y: 20 != 90
Step 13 failed:
        objects agent_female distance: 5.9186692237854 != 6.13
        objects agent_female position_x: 0.8999999761581421 != 1.0
        objects agent_female position_z: 1.7999999523162842 != 2.0
        objects agent_female rotation_y: 180 != 88
        objects agent_male direction_y: -0.1669566035270691 != -0.18
        objects agent_male distance: 4.564060211181641 != 4.45
        objects agent_male position_z: 0.5 != 0.38
        objects agent_male rotation_y: 110 != 180
        objects soccer_ball direction_y: -0.1669566035270691 != -0.18
        objects soccer_ball distance: 4.564060211181641 != 4.45
        objects soccer_ball position_z: 0.5 != 0.38
        objects soccer_ball rotation_y: 20 != 90
Step 14 failed:
        objects agent_female distance: 5.9186692237854 != 6.13
        objects agent_female position_x: 0.8999999761581421 != 1.0
        objects agent_female position_z: 1.7999999523162842 != 2.0
        objects agent_female rotation_y: 180 != 119
        objects agent_male direction_y: -0.1669566035270691 != -0.18
        objects agent_male distance: 4.564060211181641 != 4.37
        objects agent_male position_z: 0.5 != 0.34
        objects agent_male rotation_y: 110 != 180
        objects soccer_ball direction_y: -0.1669566035270691 != -0.18
        objects soccer_ball distance: 4.564060211181641 != 4.37
        objects soccer_ball position_z: 0.5 != 0.34
        objects soccer_ball rotation_y: 20 != 90
Step 15 failed:
        objects agent_female distance: 5.9186692237854 != 6.13
        objects agent_female position_x: 0.8999999761581421 != 1.0
        objects agent_female position_z: 1.7999999523162842 != 2.0
        objects agent_female rotation_y: 180 != 149
        objects agent_male direction_y: -0.1669566035270691 != -0.18
        objects agent_male distance: 4.564060211181641 != 4.37
        objects agent_male position_z: 0.5 != 0.3
        objects agent_male rotation_y: 110 != 180
        objects soccer_ball direction_y: -0.1669566035270691 != -0.18
        objects soccer_ball distance: 4.564060211181641 != 4.37
        objects soccer_ball position_z: 0.5 != 0.3
        objects soccer_ball rotation_y: 20 != 90
Step 16 failed:
        objects agent_female distance: 5.9186692237854 != 6.13
        objects agent_female position_x: 0.8999999761581421 != 1.0
        objects agent_female position_z: 1.7999999523162842 != 2.0
        objects agent_male direction_y: -0.1669566035270691 != -0.18
        objects agent_male distance: 4.564060211181641 != 4.33
        objects agent_male position_z: 0.5 != 0.26
        objects agent_male rotation_y: 110 != 180
        objects soccer_ball direction_y: -0.1669566035270691 != -0.18
        objects soccer_ball distance: 4.564060211181641 != 4.33
        objects soccer_ball position_z: 0.5 != 0.26
        objects soccer_ball rotation_y: 20 != 90
Step 17 failed:
        objects agent_female distance: 5.9186692237854 != 6.09
        objects agent_female position_x: 0.8999999761581421 != 1.0
        objects agent_female position_z: 1.7999999523162842 != 1.96
        objects agent_male direction_y: -0.1669566035270691 != -0.18
        objects agent_male distance: 4.564060211181641 != 4.29
        objects agent_male position_z: 0.5 != 0.22
        objects agent_male rotation_y: 110 != 180
        objects soccer_ball direction_y: -0.1669566035270691 != -0.18
        objects soccer_ball distance: 4.564060211181641 != 4.29
        objects soccer_ball position_z: 0.5 != 0.22
        objects soccer_ball rotation_y: 20 != 90
Step 18 failed:
        objects agent_female direction_x: 0.15206120908260345 != 0.17
        objects agent_female distance: 5.9186692237854 != 6.05
        objects agent_female position_x: 0.8999999761581421 != 1.0
        objects agent_female position_z: 1.7999999523162842 != 1.92
        objects agent_male direction_y: -0.1669566035270691 != -0.18
        objects agent_male distance: 4.564060211181641 != 4.25
        objects agent_male position_z: 0.5 != 0.18
        objects agent_male rotation_y: 110 != 180
        objects soccer_ball direction_y: -0.1669566035270691 != -0.18
        objects soccer_ball distance: 4.564060211181641 != 4.25
        objects soccer_ball position_z: 0.5 != 0.18
        objects soccer_ball rotation_y: 20 != 90
Step 19 failed:
        objects agent_female direction_x: 0.15206120908260345 != 0.17
        objects agent_female distance: 5.9186692237854 != 6.0
        objects agent_female position_x: 0.8999999761581421 != 1.0
        objects agent_female position_z: 1.7999999523162842 != 1.88
        objects agent_male direction_y: -0.1669566035270691 != -0.19
        objects agent_male distance: 4.564060211181641 != 4.21
        objects agent_male position_z: 0.5 != 0.14
        objects agent_male rotation_y: 110 != 180
        objects soccer_ball direction_y: -0.1669566035270691 != -0.19
        objects soccer_ball distance: 4.564060211181641 != 4.21
        objects soccer_ball position_z: 0.5 != 0.14
        objects soccer_ball rotation_y: 20 != 90
Step 20 failed:
        objects agent_female position_x: 0.8999999761581421 != 1.0
        objects agent_female position_z: 1.7999999523162842 != 1.84
        objects agent_male direction_y: -0.1669566035270691 != -0.19
        objects agent_male distance: 4.564060211181641 != 4.21
        objects agent_male position_z: 0.5 != 0.14
        objects agent_male rotation_y: 110 != 180
        objects soccer_ball direction_y: -0.1669566035270691 != -0.19
        objects soccer_ball distance: 4.564060211181641 != 4.21
        objects soccer_ball position_z: 0.5 != 0.14
        objects soccer_ball rotation_y: 20 != 90
Step 21 failed:
        objects agent_female position_x: 0.8999999761581421 != 1.0
        objects agent_male direction_y: -0.1669566035270691 != -0.19
        objects agent_male distance: 4.564060211181641 != 4.21
        objects agent_male position_z: 0.5 != 0.14
        objects agent_male rotation_y: 110 != 180
        objects soccer_ball direction_y: -0.1669566035270691 != -0.19
        objects soccer_ball distance: 4.564060211181641 != 4.21
        objects soccer_ball position_z: 0.5 != 0.14
        objects soccer_ball rotation_y: 20 != 90
Step 22 failed:
        objects agent_female position_x: 0.8999999761581421 != 1.0
        objects agent_female position_z: 1.7999999523162842 != 1.76
        objects agent_male direction_y: -0.1669566035270691 != -0.19
        objects agent_male distance: 4.564060211181641 != 4.21
        objects agent_male position_z: 0.5 != 0.14
        objects agent_male rotation_y: 110 != 180
        objects soccer_ball direction_y: -0.1669566035270691 != -0.19
        objects soccer_ball distance: 4.564060211181641 != 4.21
        objects soccer_ball position_z: 0.5 != 0.14
        objects soccer_ball rotation_y: 20 != 90
Step 23 failed:
        objects agent_female direction_x: 0.15206120908260345 != 0.17
        objects agent_female position_x: 0.8999999761581421 != 1.0
        objects agent_female position_z: 1.7999999523162842 != 1.72
        objects agent_male direction_y: -0.1669566035270691 != -0.18
        objects agent_male distance: 4.564060211181641 != 4.21
        objects agent_male position_z: 0.5 != 0.14
        objects agent_male rotation_y: 110 != 180
        objects soccer_ball direction_y: -0.1669566035270691 != -0.18
        objects soccer_ball distance: 4.564060211181641 != 4.21
        objects soccer_ball position_z: 0.5 != 0.14
        objects soccer_ball rotation_y: 20 != 90
Step 24 failed:
        objects agent_female direction_x: 0.15206120908260345 != 0.17
        objects agent_female distance: 5.9186692237854 != 5.82
        objects agent_female position_x: 0.8999999761581421 != 1.0
        objects agent_female position_z: 1.7999999523162842 != 1.68
        objects agent_male direction_y: -0.1669566035270691 != -0.18
        objects agent_male distance: 4.564060211181641 != 4.21
        objects agent_male position_z: 0.5 != 0.14
        objects agent_male rotation_y: 110 != 180
        objects soccer_ball direction_y: -0.1669566035270691 != -0.18
        objects soccer_ball distance: 4.564060211181641 != 4.21
        objects soccer_ball position_z: 0.5 != 0.14
        objects soccer_ball rotation_y: 20 != 90
Step 25 failed:
        objects agent_female direction_x: 0.15206120908260345 != 0.17
        objects agent_female distance: 5.9186692237854 != 5.82
        objects agent_female position_x: 0.8999999761581421 != 1.0
        objects agent_female position_z: 1.7999999523162842 != 1.68
        objects agent_male direction_y: -0.1669566035270691 != -0.18
        objects agent_male distance: 4.564060211181641 != 4.21
        objects agent_male position_z: 0.5 != 0.14
        objects agent_male rotation_y: 110 != 180
        objects soccer_ball direction_y: -0.1669566035270691 != -0.18
        objects soccer_ball distance: 4.564060211181641 != 4.21
        objects soccer_ball position_z: 0.5 != 0.14
        objects soccer_ball rotation_y: 20 != 90
Step 26 failed:
        objects agent_female direction_x: 0.15206120908260345 != 0.17
        objects agent_female distance: 5.9186692237854 != 5.82
        objects agent_female position_x: 0.8999999761581421 != 1.0
        objects agent_female position_z: 1.7999999523162842 != 1.68
        objects agent_male direction_y: -0.1669566035270691 != -0.18
        objects agent_male distance: 4.564060211181641 != 4.21
        objects agent_male position_z: 0.5 != 0.14
        objects agent_male rotation_y: 110 != 180
        objects soccer_ball direction_y: -0.1669566035270691 != -0.18
        objects soccer_ball distance: 4.564060211181641 != 4.21
        objects soccer_ball position_z: 0.5 != 0.14
        objects soccer_ball rotation_y: 20 != 90
Step 27 failed:
        objects agent_female direction_x: 0.15206120908260345 != 0.17
        objects agent_female distance: 5.9186692237854 != 5.82
        objects agent_female position_x: 0.8999999761581421 != 1.0
        objects agent_female position_z: 1.7999999523162842 != 1.68
        objects agent_male direction_y: -0.1669566035270691 != -0.18
        objects agent_male distance: 4.564060211181641 != 4.13
        objects agent_male position_z: 0.5 != 0.06
        objects agent_male rotation_y: 110 != 180
        objects soccer_ball direction_y: -0.1669566035270691 != -0.18
        objects soccer_ball distance: 4.564060211181641 != 4.13
        objects soccer_ball position_z: 0.5 != 0.06
        objects soccer_ball rotation_y: 20 != 90
Step 28 failed:
        objects agent_female direction_x: 0.15206120908260345 != 0.17
        objects agent_female distance: 5.9186692237854 != 5.82
        objects agent_female position_x: 0.8999999761581421 != 1.0
        objects agent_female position_z: 1.7999999523162842 != 1.68
        objects agent_male direction_y: -0.1669566035270691 != -0.19
        objects agent_male distance: 4.564060211181641 != 4.09
        objects agent_male position_z: 0.5 != 0.02
        objects agent_male rotation_y: 130 != 180
        objects soccer_ball direction_y: -0.1669566035270691 != -0.19
        objects soccer_ball distance: 4.564060211181641 != 4.09
        objects soccer_ball position_z: 0.5 != 0.02
        objects soccer_ball rotation_y: 40 != 90
Step 29 failed:
        objects agent_female direction_x: 0.15206120908260345 != 0.17
        objects agent_female distance: 5.9186692237854 != 5.82
        objects agent_female position_x: 0.8999999761581421 != 1.0
        objects agent_female position_z: 1.7999999523162842 != 1.68
        objects agent_male direction_y: -0.1669566035270691 != -0.19
        objects agent_male distance: 4.564060211181641 != 4.05
        objects agent_male position_z: 0.5 != -0.02
        objects agent_male rotation_y: 150 != 180
        objects soccer_ball direction_y: -0.1669566035270691 != -0.19
        objects soccer_ball distance: 4.564060211181641 != 4.05
        objects soccer_ball position_z: 0.5 != -0.02
        objects soccer_ball rotation_y: 60 != 90
Step 30 failed:
        objects agent_female direction_x: 0.15206120908260345 != 0.17
        objects agent_female distance: 5.9186692237854 != 5.82
        objects agent_female position_x: 0.8999999761581421 != 1.0
        objects agent_female position_z: 1.7999999523162842 != 1.68
        objects agent_male direction_y: -0.1669566035270691 != -0.19
        objects agent_male distance: 4.564060211181641 != 4.01
        objects agent_male position_z: 0.5 != -0.06
        objects soccer_ball direction_y: -0.1669566035270691 != -0.19
        objects soccer_ball distance: 4.564060211181641 != 4.01
        objects soccer_ball position_z: 0.5 != -0.06
```

**Comment by jaudick** [comment]
@ThomasSchellenbergNextCentury I cannot replicate that error so I'm not sure whats going on. I'm curious if anyone else had the same issue. When they are frozen do they appear to instantly reset to their idle pose like these images or do they freeze in a walking animation?
Screenshot from 2022-05-11 14-28-08
Screenshot from 2022-05-11 14-29-09

**Comment by ThomasSchellenbergNextCentury** [comment]
This is what the test looks like for me (which I got by adding `video_enabled: true` to `integration_tests/config_oracle.ini`):

https://user-images.githubusercontent.com/10994382/167927836-0fe673e5-5c05-4981-8e12-4be6ffeb220c.mp4

If this doesn't look right, I'll try rebuilding everything this evening, in case it _was_ a build issue. (Please make sure you've pushed all commits on your branches.)

**Comment by ThomasSchellenbergNextCentury** [comment]
Ugh, I forgot `video_enabled` doesn't emit a web-ready video. Here's one from ffmpeg:

https://user-images.githubusercontent.com/10994382/167928751-2acf7b0e-134b-42a6-92b1-d0e390db76da.mp4

**Comment by jaudick** [comment]
That does not look right at all. I believe I pushed the necessary changes on both the private and unity branches too based on my commit history. I'll rebuild too making sure I'm on all the correct branches

**Comment by jaudick** [comment]
@ThomasSchellenbergNextCentury I pushed one addressables update on the unity branch from rebuilding maybe that will fix it

**Comment by ThomasSchellenbergNextCentury** [comment]
Thanks! The tests appear to be working now (either because of the commit you made, or rebuilding on my end). However, I still see a lot of movement in the test. Is this right?

https://user-images.githubusercontent.com/10994382/168070514-2c59961a-8891-4ed8-8b2b-1ba4965ffbaa.mp4

**Review by kdrumm — APPROVED** [review]

**Review by ThomasSchellenbergNextCentury — APPROVED** [review]
Sounds good. Thanks for the confirmation.

**Pull request merged**
