### PR TITLE
Separate lid config and integration tests

### PR DESCRIPTION
**Pull request by jaudick**
[Unity](https://github.com/NextCenturyCorporation/ai2thor/compare/development...NextCenturyCorporation:ai2thor:MCS-1489-seperate-lid?expand=1)
[Private](https://github.com/NextCenturyCorporation/mcs-private/pull/301)

### CODE REVIEW

**Review by brianpippin — APPROVED** [review]
Just approving the tests in MCS, they look good.

**Comment by rartiss55** [comment]
Not sure if its just me, but all my tests pass except for `094.platform_lips` level1 and level2.

**Review by ThomasSchellenbergNextCentury — APPROVED** [review]

**Comment by ThomasSchellenbergNextCentury** [comment]
@rartiss55 Brian fixed that the other day. Maybe the latest from `development` hasn't been merged in yet?

**Comment by brianpippin** [comment]
> @rartiss55 Brian fixed that the other day. Maybe the latest from `development` hasn't been merged in yet?

I was coming to say this was a small fix added to development recently, but Thomas was too quick for me.

**Comment by rartiss55** [comment]
@ThomasSchellenbergNextCentury @brianpippin Well thank you both for your quick reply :)

**Review by rartiss55 — APPROVED** [review]

**Pull request merged**
