### PR TITLE
Empty and huge room lighting tests

### PR DESCRIPTION
**Pull request by jaudick**
I had originally created tests for _playroom rotate 360 from the center_ and _agents walking and animating_ but I could not get them to work. The **truth images** are generated by from the saved images in **human input mode**. Visually you could see the slight aliasing pixel difference on objects and agents when comparing exported images here and the human input ones. It was less a lighting issue and more a resolution issue. For now empty rooms are all that's implemented but the core functionality is here.
[
Please use this branch](https://github.com/NextCenturyCorporation/ai2thor/pull/241)

### CODE REVIEW

**Review by kdrumm — COMMENTED** [review]
These tests are failing for me using the latest development build.  I'm afraid the exact pixels are too dependent on hardware to make tests like this work consistently.  Has anyone else tried?

**Comment by ThomasSchellenbergNextCentury** [comment]
I'm also getting failures. Here's what I'm seeing:

```
$ python integration_tests/run_handmade_tests.py --mcs_unity_version development --test run_empty_room_lighting_test --dev
========================================
HANDMADE TEST METADATA TIER: LEVEL1
Found path: /home/tschellenberg/.mcs/develop/MCS-AI2-THOR-Unity-App-vdevelop.x86_64
RUNNING TESTS: run_empty_room_lighting_test
========================================
HANDMADE TEST METADATA TIER: LEVEL2
RUNNING TESTS: run_empty_room_lighting_test
========================================
HANDMADE TEST METADATA TIER: ORACLE
RUNNING TESTS: run_empty_room_lighting_test
========================================
SUCCESSFUL INTEGRATION TESTS:
    NONE
FAILED INTEGRATION TESTS:
    run_empty_room_lighting_test (level1): Step 1 failed: image lighting comparision [1279225.0, 1510402.0, 923283.0] != [0.0, 0.0, 0.0]
    run_empty_room_lighting_test (level2): Step 1 failed: image lighting comparision [1279225.0, 1510402.0, 923283.0] != [0.0, 0.0, 0.0]
    run_empty_room_lighting_test (oracle): Step 1 failed: image lighting comparision [1279225.0, 1510402.0, 923283.0] != [0.0, 0.0, 0.0]
```

```
$ python integration_tests/run_handmade_tests.py --mcs_unity_version development --test run_huge_room_lighting_test --dev
========================================
HANDMADE TEST METADATA TIER: LEVEL1
Found path: /home/tschellenberg/.mcs/develop/MCS-AI2-THOR-Unity-App-vdevelop.x86_64
RUNNING TESTS: run_huge_room_lighting_test
========================================
HANDMADE TEST METADATA TIER: LEVEL2
RUNNING TESTS: run_huge_room_lighting_test
========================================
HANDMADE TEST METADATA TIER: ORACLE
RUNNING TESTS: run_huge_room_lighting_test
========================================
SUCCESSFUL INTEGRATION TESTS:
    NONE
FAILED INTEGRATION TESTS:
    run_huge_room_lighting_test (level1): Step 1 failed: image lighting comparision [8471.0, 10148.0, 5587.0] != [0.0, 0.0, 0.0]
    run_huge_room_lighting_test (level2): Step 1 failed: image lighting comparision [8471.0, 10148.0, 5587.0] != [0.0, 0.0, 0.0]
    run_huge_room_lighting_test (oracle): Step 1 failed: image lighting comparision [8471.0, 10148.0, 5587.0] != [0.0, 0.0, 0.0]
```

I don't have a better guess than Kyle's (that there are extremely small differences depending on hardware and/or floating point arithmetic). Maybe this endeavor was not destined to succeed...  :frowning_face:

**Comment by jaudick** [comment]
@ThomasSchellenbergNextCentury @kdrumm I get this running on dev
`python run_tests.py --mcs_unity_build_file_path ../../unity/dev/dev.x86_64 --dev --test run_huge_room_lighting_test 
========================================
HANDMADE TEST METADATA TIER: LEVEL1
Set current directory to /home/jaudick@hq.nextcentury.com/Documents/MCS/integration_tests
Found path: /home/jaudick@hq.nextcentury.com/Documents/MCS/integration_tests/../../unity/dev/dev.x86_64
RUNNING TESTS: run_huge_room_lighting_test
========================================
HANDMADE TEST METADATA TIER: LEVEL2
RUNNING TESTS: run_huge_room_lighting_test
========================================
HANDMADE TEST METADATA TIER: ORACLE
RUNNING TESTS: run_huge_room_lighting_test
========================================
SUCCESSFUL INTEGRATION TESTS:
    run_huge_room_lighting_test (level1)
    run_huge_room_lighting_test (level2)
    run_huge_room_lighting_test (oracle)
FAILED INTEGRATION TESTS:
    NONE
`

I am ok letting this endeavor be put to rest based on what appears to be hardware differences. At least it was attempted and we now know. If we're in favor, this can be closed...

**Comment by ThomasSchellenbergNextCentury** [comment]
I've retried with Jacob's latest files, but the tests are still failing for me. I'm going to go ahead and close this PR.

**Pull request closed without merging**
