### PR TITLE
MCS-1490 added globalSpace property for moves and fixed separate lid opening at angle based on ILE discoveries

### PR DESCRIPTION
**Pull request by jaudick**
[Unity](https://github.com/NextCenturyCorporation/ai2thor/pull/288)
I also got rid of a bunch of unused lines from the previous integration tests I made that I forgot to delete hence the 16k deletions

### CODE REVIEW

**Review by brianpippin — DISMISSED** [review]

**Comment by rartiss55** [comment]
Getting an error for test 173:

FAILED INTEGRATION TESTS:
    173.attachable_lid_at_angle (level1): Step 42 failed:
        head_tilt: 20 != 10
        return_status: UNDEFINED != SUCCESSFUL
    173.attachable_lid_at_angle (level2): Step 42 failed:
        head_tilt: 20 != 10
        return_status: UNDEFINED != SUCCESSFUL
    173.attachable_lid_at_angle (oracle): Step 43 failed:
        objects container_1 visible: True != False

**Review by ThomasSchellenbergNextCentury — CHANGES_REQUESTED** [review]
1. I'm getting the same errors Rachel saw for test 173
2. I'm also getting errors on steps 1-25 of test 174 at oracle level, concerning the direction/distance/position. Here are the first few steps:

```
Step 1 failed:
        objects container_1 distance: 2.7615609169006348 != 2.81
        objects container_1 position_x: -0.21613295376300812 != -0.2
        objects container_1 position_z: 0.14553609490394592 != 0.2
Step 2 failed:
        objects container_1 direction_y: -0.28180131316185 != -0.27
        objects container_1 distance: 2.7040326595306396 != 2.81
        objects container_1 position_x: -0.13226589560508728 != -0.1
        objects container_1 position_z: 0.0910721868276596 != 0.2
Step 3 failed:
        objects container_1 direction_x: -0.01827039010822773 != -0.0
        objects container_1 direction_y: -0.28765228390693665 != -0.27
        objects container_1 distance: 2.649031400680542 != 2.81
        objects container_1 position_x: -0.04839883744716644 != -0.0
        objects container_1 position_z: 0.03660828247666359 != 0.2
```

3. The lid isn't opening correct in test 173. There's a big gap between the bottom and the lid:

frame_image_38

**Comment by brianpippin** [comment]
I might have to rebuild this and try again since everyone else is getting errors.

**Comment by jaudick** [comment]
@ThomasSchellenbergNextCentury @brianpippin @rartiss55 I made a very minor float change on the container prefabs receptacle box on [private ](https://github.com/NextCenturyCorporation/mcs-private/pull/313) that may fix the issue. I really didnt think it would make a difference so thats why i pushed this pr separately from the private one but please try building again again. @ThomasSchellenbergNextCentury I cannot replicate your errors with the lid being off when running the build from the [unity branch](https://github.com/NextCenturyCorporation/ai2thor/pull/288/files). The unity pr was meant to fix that issue so I really believe the most recent push should fix it. Could you guys please try one more time with the most recent push from unity and the newly updated private assets

**Comment by ThomasSchellenbergNextCentury** [comment]
@jaudick I'm unfortunately seeing the same issues (I copied over the new prefab, rebuilt my local addressables, removed the cached addressables from my `/tmp/` folder, and reran the tests). I wonder if you're not testing using the same prefab we are? Whenever I copy over the new `cube_hollow_with_bottom_lid.prefab` from the `mcs-private` repo into the `ai2thor` repo, I notice it's not marked as an Addressable. I have to mark it as an Addressable, move it to the Container Prefabs asset group, and click Save Project, before I build my addressables locally. (Looking at the diff for the `Container Prefabs.asset` file, I guess it has a new GUID?) Jacob, could you try copying over the prefab file from the `mcs-private` repo into `ai2thor`, making sure it's marked as Addressable, rebuilding your addressables locally, and running your integration tests again? That's my only idea right now.

**Comment by rartiss55** [comment]
I'm still getting the error I was seeing for 173, but I'm not seeing the separate lid issue Thomas was seeing/174 passes fine for me. I copied assets from the MCS-1490-containers-with-separate-lids mcs-private branch and was on the 1490 branch for ai2thor (looks like I have latest for everything as well). Curious what others are seeing.

**Comment by ThomasSchellenbergNextCentury** [comment]
I'm still seeing the same issues as before. However, since Rachel isn't (just the initial errors for 173), I'm going to assume the lid issue is just on my end. I'll dig into it. For reference, here's what I did:

1. In `mcs-private`, checkout the MCS-1490 branch and pull the latest
2. Copy files from `<mcs-private>/UnityAssetStore/Custom/*` into `<ai2thor>/unity/Assets/Addressables/MCS/UnityAssetStore/Custom/`
3. In `ai2thor`, checkout the MCS-1490 branch and pull the latest
4. Delete the `<ai2thor>/unity/ServerData/` folder
5. In the Unity Editor, first click `Window->Asset Management->Addressables->Groups`, then `Build->Clean Build->All`, and finally `Build->New Build->Default Build Script`
6. Build the Unity executable
7. Delete my locally cached addressables: `rm -rf /tmp/CACI\ with\ the\ Allen\ Institute\ for\ Artificial\ Intelligence_MCS-AI2-THOR/`
8. In the new ServerData/ folder, run `sudo python3 -m http.server 80`
9. In `mcs`, checkout the MCS-1490 branch and pull the latest
10. Run: `source venv/bin/activate`
11. Then run the integration tests: `python integration_tests/run_tests.py --mcs_unity_build <mcs-unity-exe> --test 173 --dev` (and also test 174)

**Comment by ThomasSchellenbergNextCentury** [comment]
Ugh... I rebuilt everything locally, and I thought I had a breakthrough, because Unity was accidentally saving the executable as `MCS-AI2-THOR-Unity-App-v0.6.0x86_64.x86_64` (notice the extra `x86_64`?).

But now my test 173 is even wackier... I kept at it...

https://user-images.githubusercontent.com/10994382/199313528-d50e3c78-5d10-4c7c-aa59-41078cb01d08.mp4

**Comment by jaudick** [comment]
@ThomasSchellenbergNextCentury @rartiss55  Could you rerun these tests with the latest commit from the unity branch. I fixed the not visible on [step 43](https://github.com/NextCenturyCorporation/MCS/pull/622/commits/f7facf1d81d95d5f0dcb504b1a8d67278b3711c3). I also changed the[ head tilts](https://github.com/NextCenturyCorporation/MCS/pull/622/commits/fac31833f69739919cee167054bf012af50a7f07) and [return status](https://github.com/NextCenturyCorporation/MCS/pull/622/commits/15e52285fcc277180d940ae419b9882da6b1d90f) to be accurate.

**Comment by ThomasSchellenbergNextCentury** [comment]
I got tests 173 and 174 working! Hallelujah. However:
1. I had to merge `development` into the MCS-1490 `ai2thor` branch for some of the other integration tests to pass.
2. Test 170 is failing for me, I think due to the recent changes made by @jaudick 

```
RUNNING SCENE: 170.attachable_lid.scene.json
Step 33 failed:
        return_status: SUCCESSFUL != UNDEFINED
Step 34 failed:
        return_status: SUCCESSFUL != UNDEFINED
Step 38 failed:
        return_status: SUCCESSFUL != UNDEFINED
Step 39 failed:
        return_status: SUCCESSFUL != UNDEFINED
Step 40 failed:
        return_status: SUCCESSFUL != UNDEFINED
Step 43 failed:
        return_status: SUCCESSFUL != UNDEFINED
Step 68 failed:
        return_status: SUCCESSFUL != UNDEFINED
Step 76 failed:
        return_status: SUCCESSFUL != UNDEFINED
Step 101 failed:
        return_status: SUCCESSFUL != UNDEFINED
Step 102 failed:
        return_status: SUCCESSFUL != UNDEFINED
Step 108 failed:
        return_status: SUCCESSFUL != UNDEFINED
Step 109 failed:
        return_status: SUCCESSFUL != UNDEFINED
```

But we're very close!

**Comment by jaudick** [comment]
@ThomasSchellenbergNextCentury I updated 170

**Review by brianpippin — APPROVED** [review]

**Pull request merged**
