### PR TITLE
MCS-1301: Enable Unity Top-Down Plotter, and Set Screenshot Folder, via Python Config

### PR DESCRIPTION
**Pull request by alexcraneunity**
This is the second part of the changes needed by MCS-1301, the first part being https://github.com/NextCenturyCorporation/ai2thor/pull/243.

This allows us to enable top-down recording, and set the directory for the saved images, through Python.

### CODE REVIEW

**Review by ThomasSchellenbergNextCentury — APPROVED** [review]
I left a couple of comments on the corresponding Unity PR, but I think they mainly affect Unity code. The python changes look good though!

**Review by brianpippin — APPROVED** [review]
The python changes look good.  Have yet to fully review unity changes.

**Review by kdrumm — COMMENTED** [review]
My integration tests are printing a bunch of 5s.  I don't see how it would be from this PR, but this is the first time I've seen it.  Anyone else see it?

**Review by kdrumm — APPROVED** [review]

**Review by jaudick — APPROVED** [review]

**Comment by jaudick** [comment]
If i run the run_human_input.py script now with just 
`
[MCS]
video_enabled: true
`
and nothing else in the config the application freezes on 
`Resetting the current scene...` 
Running the script on dev with that config works as intended. Is a topDownImage path always required now if video is enabled?

**Comment by ThomasSchellenbergNextCentury** [comment]
> Is a topDownImage path always required now if video is enabled?

@jaudick Yes, I think we decided on that behavior, since that's what happens with the current top-down plotter. Out of curiosity, what's the `"name"` property of your scene? Could it be having trouble processing some characters like whitespaces?

**Comment by kdrumm** [comment]
> > Is a topDownImage path always required now if video is enabled?
> 
> @jaudick Yes, I think we decided on that behavior, since that's what happens with the current top-down plotter. Out of curiosity, what's the `"name"` property of your scene? Could it be having trouble processing some characters like whitespaces?

Just to make sure this is clear, `topDownImagePath` isn't required in the config.  It isn't even read from the config.

**Comment by ThomasSchellenbergNextCentury** [comment]
> Just to make sure this is clear, topDownImagePath isn't required in the config. It isn't even read from the config.

Oh, thanks Kyle, I totally misread Jacob's comment.

**Comment by jaudick** [comment]
@ThomasSchellenbergNextCentury The name property was 'playroom'. So based on @kdrumm 's comment of it not being read from the config, what would a valid config with `video_enabled: true` be now to make the script run?

**Comment by kdrumm** [comment]
> @ThomasSchellenbergNextCentury The name property was 'playroom'. So based on @kdrumm 's comment of it not being read from the config, what would a valid config with `video_enabled: true` be now to make the script run?

Just having `video_enabled: true` should turn it on.  I can rebuild mine and try again.

**Review by kdrumm — CHANGES_REQUESTED** [review]
It looks like if you run this twice with the same file, it doesn't clear the `Screenshots` directory.  Either we need to put the files in the base output directory or we need to update clearing the output directory in controller.py lines 182 - 183

**Comment by kdrumm** [comment]
> @ThomasSchellenbergNextCentury The name property was 'playroom'. So based on @kdrumm 's comment of it not being read from the config, what would a valid config with `video_enabled: true` be now to make the script run?

I was able to rebuild addressables and the Unity build and run playroom with a variety of configs.  Here is one of mine I use specifically for creating videos:
```
[MCS]
history_enabled: false
metadata: level1
save_debug_images: false
save_debug_json: false
video_enabled: true

steps_allowed_in_lava: 2
```

**Comment by jaudick** [comment]
Even with that config I can't get this run this run after rebuilding the unity build several times on 1301. Whenever `video_enabled: true` it gets hung on `Resetting the current scene...` on the first frame. I can see the playroom scene loaded but I cannot enter input. However, when its false it runs as normal.

**Comment by kdrumm** [comment]
@jaudick Are you running in a terminal or in VS code?  If you're running in VS code, it'd be interesting to see where the execution is if you stop it.  Also, try manually deleting the `playroom` folder where the files are going.  There is a bug where this code doesn't remove that yet and crashes after `Resetting the current scene...`.  If that fixes it, we should figure out why you aren't getting a stack trace.  It could be a logging configuration issue.

**Comment by jaudick** [comment]
@kdrumm I was running in the terminal and even after deleting the playroom folder it still holds on the issue, I'll try running in vscode

**Comment by jaudick** [comment]
It freezes at line 191 in controller.py 
```
ai2thor_step = self.parameter_converter.wrap_step(
            output_folder=self.__output_folder,
            action='Initialize',
            sceneConfig=sc)
step_output = self._controller.step(ai2thor_step) <---191 HERE!!!
```
Here is the value of the step:
Screenshot from 2022-05-12 16-55-50

**Comment by kdrumm** [comment]
@jaudick This is strange and I think we need to figure it out.  If the same problem happens during an eval we'd be in trouble.  I couldn't step the debugger into the AI2THOR code for `_controller.step()`, but you can `ctrl+click` to go into the file and edit it.  You could add print statements to get a more refined location of the problem.  I'd be curious to know if it is in transmission.  Another Idea would be to run the debugger in the unity app.  Lastly, you could rebuild your mcs virtual environment.  

Have both @ThomasSchellenbergNextCentury and @brianpippin successfully ran this without any issues?

**Comment by ThomasSchellenbergNextCentury** [comment]
@kdrumm I'm able to successfully run the playroom scene (among others) using the config file you posted and see the top-down images.

@jaudick Can you run other scenes successfully, and it's just the playroom file that's failing? Or do all scene files fail? Your failure reminds me of an issue I had when my local addressables weren't built correctly. Maybe try rebuilding your local addressables?

**Comment by jaudick** [comment]
All of the scene fail when video_enabled is true but run when false, I'll try rebuilding my addressables but I found where it hangs at line 88 in fifo_server.py:
```
    def _recv_message(self):
        if self.server_pipe is None:
            self.server_pipe = open(self.server_pipe_path, "rb")

        metadata = None
        files = defaultdict(list)
        while True:
            header = self.server_pipe.read( <-----Here
                self.header_size)  # message type + length <-----Here
```

**Comment by jaudick** [comment]
@ThomasSchellenbergNextCentury @kdrumm It looks like rebuilding my addressables fixed it. Not sure why that was the fix given it worked with all other configs except video enabled being true. The only issue is [kyles comment](https://github.com/NextCenturyCorporation/MCS/pull/572#pullrequestreview-971366209) but other than that this looks good and even works with large rooms.

**Review by kdrumm — APPROVED** [review]

**Review by kdrumm — COMMENTED** [review]
Sorry, I forgot to run integration tests before approving.  They are currently running, but I already got some failures mainly due to ceiling distance errors.  Is this due to not having both branches merged with master?

**Comment by alexcraneunity** [comment]
@kdrumm  This is actually because the Unity branch is based off of [MCS-1178](https://github.com/NextCenturyCorporation/ai2thor/pull/224), which has those integration test issues due to changing the ceiling game object. What I suggest is merging the [Unity PR](https://github.com/NextCenturyCorporation/ai2thor/pull/243) into MCS-1178, then resolving that code review before we merge this one into development.

**Comment by ThomasSchellenbergNextCentury** [comment]
@alexcraneunity I merged in the branch as you suggested, and merged the `development` branches for both `MCS` and `ai2thor` in as well, and rebuilt my local addressables, but I'm also seeing integration test errors with the ceiling. I think these values will need to be updated due to changes in the ceiling's position from the top-down plotter branch (MCS-1178).

```
FAILED INTEGRATION TESTS:
    001.empty_room_movement (oracle): Step 0 failed:
        structural_objects ceiling distance: 2.23799991607666 != 2.488
    063.wall_material (oracle): Step 0 failed:
        structural_objects ceiling distance: 2.23799991607666 != 2.488
    064.wall_material_2 (oracle): Step 0 failed:
        structural_objects ceiling distance: 2.23799991607666 != 2.488
    065.platform (oracle): Step 0 failed:
        structural_objects ceiling direction_x: -0.30485132336616516 != -0.292
        structural_objects ceiling direction_y: 0.8613066077232361 != 0.874
        structural_objects ceiling direction_z: -0.4064684510231018 != -0.389
        structural_objects ceiling distance: 4.920431137084961 != 5.137
    094.platform_lips (oracle): Step 0 failed:
        structural_objects ceiling distance: 2.98799991607666 != 3.238
```

**Comment by alexcraneunity** [comment]
Thank you @ThomasSchellenbergNextCentury. I was able to fix the failing tests for the ceiling object, but I noticed that one of the failed tests involves the soccer ball object. I don't believe this is related to my changes, so I'm wondering if I should fix it or ignore it for the time being. 
`FAILED INTEGRATION TESTS:
    109.soccer_ball (oracle): Step 28 failed:
        objects soccer_ball position_x: 0.010031532496213913 != 0.0
`

**Comment by kdrumm** [comment]
> @alexcraneunity I ran the tests again and didn't get any failures. It appears test 109 might only fail intermittently? @kdrumm I think you might have seen this before as well? Regardless, I'm thinking Alex is correct in saying that the failure in test 109 isn't related to his PR, and that it shouldn't hold up its approval (and we can make a separate ticket to investigate the issue further).

I think you are correct.  re-approved from me.

**Review by jaudick — APPROVED** [review]

**Review by brianpippin — APPROVED** [review]
This is ready to be merged.

**Pull request merged**
