### PR TITLE
MCS-1186 Added integration tests for tool objects.

### PR DESCRIPTION
**Pull request by ThomasSchellenbergNextCentury**
Corresponding Unity PR: https://github.com/NextCenturyCorporation/ai2thor/pull/212

(You'll need to rebuild your addressables!)

### CODE REVIEW

**Review by kdrumm — COMMENTED** [review]
I am getting failures on the new tests.  I suspect my addressables isn't building right though as one of the errors is the tools material list is ['WOOD'], but I can see the registry lists them as 'metal'

**Comment by ThomasSchellenbergNextCentury** [comment]
@kdrumm Yeah, I pushed the "metal" fix yesterday evening, so if you haven't rebuilt your addressables since then, you need to do so.

**Comment by kdrumm** [comment]
> @kdrumm Yeah, I pushed the "metal" fix yesterday evening, so if you haven't rebuilt your addressables since then, you need to do so.

Yeah, I've rebuilt multiple times which is why I am so confused.

**Review by kdrumm — APPROVED** [review]
Finally fixed my addressables!

**Review by jaudick — APPROVED** [review]

**Pull request merged**
