### PR TITLE
MCS-271: Transferral goal optimal path moves in incorrect direction(s)

### PR DESCRIPTION
**Pull request by chrislong**

### CODE REVIEW

**Comment by deanwetherby** [comment]
Moving in the right direction now but something is wrong with the distance calculation. My first test of a transferral goal stopped short 3 moveaheads before the target 1 object was within reach.

**Comment by chrislong** [comment]
Are you sure? Doing a simple distance calculation from the performer's start to the object shows it doing the right number of steps (7 with about .5 (of a step) left over):
`math.sqrt((3.59-4.2)**2 + (-0.66- -4.36)**2)/0.5 => 7.5`

I think the final step is .38 instead of .5 because the object's dimensions are non-zero.

**Comment by deanwetherby** [comment]
I am running the human input script and following the answer directions. Maybe the default step action is not the same?

**Comment by deanwetherby** [comment]
I skipped the dramatic horizon rotation but took the following actions. Rotate, move forward 7 times and the partial. The object is out of reach.

image

`All actions available during this step.
Enter your command:
r, rotation=81.0
You entered command:
RotateLook  rotation=81.0
===============================================================================
STEP: 1
ACTION: RotateLook
RETURN STATUS: SUCCESSFUL
OBJECTS: 1 TOTAL
    OBJECT ID                             SHAPE             COLORS  HELD   POSITION (WORLD)                    DIMENSIONS (WORLD)  DISTANCE (WORLD)  DIRECTION (WORLD)                    
    f5487b06-7a01-45d8-bbda-2cf893b7d126  blank block cube  yellow  False  (4.199999,0.100000121,-4.35999966)  None                3.77836037        (0.161913961,-0.0962195,-0.982102633)
===============================================================================
All actions available during this step.
Enter your command:
w
You entered command:
MoveAhead
===============================================================================
STEP: 2
ACTION: MoveAhead
wRETURN STATUS: SUCCESSFUL
OBJECTS: 1 TOTAL
    OBJECT ID                             SHAPE             COLORS  HELD   POSITION (WORLD)                    DIMENSIONS (WORLD)  DISTANCE (WORLD)  DIRECTION (WORLD)                    
    f5487b06-7a01-45d8-bbda-2cf893b7d126  blank block cube  yellow  False  (4.199999,0.100000113,-4.35999966)  None                3.53037834        (0.1622459,-0.103021733,-0.981357634)
===============================================================================
All actions available during this step.
Enter your command:

You entered command:
MoveAhead
===============================================================================
STEP: 3
ACTION: MoveAhead
wRETURN STATUS: SUCCESSFUL
OBJECTS: 1 TOTAL
    OBJECT ID                             SHAPE             COLORS  HELD   POSITION (WORLD)                    DIMENSIONS (WORLD)  DISTANCE (WORLD)  DIRECTION (WORLD)                     
    f5487b06-7a01-45d8-bbda-2cf893b7d126  blank block cube  yellow  False  (4.199999,0.100000121,-4.35999966)  None                3.28270221        (0.16261889,-0.110852458,-0.980442166)
===============================================================================
All actions available during this step.
Enter your command:

You entered command:
MoveAhead
===============================================================================
STEP: 4
ACTION: MoveAhead
wRETURN STATUS: SUCCESSFUL
OBJECTS: 1 TOTAL
    OBJECT ID                             SHAPE             COLORS  HELD   POSITION (WORLD)                    DIMENSIONS (WORLD)  DISTANCE (WORLD)  DIRECTION (WORLD)                  
    f5487b06-7a01-45d8-bbda-2cf893b7d126  blank block cube  yellow  False  (4.199999,0.100000121,-4.35999966)  None                3.03540754        (0.163040429,-0.1199621,-0.9792992)
===============================================================================
All actions available during this step.
Enter your command:

You entered command:
MoveAhead
===============================================================================
STEP: 5
ACTION: MoveAhead
wRETURN STATUS: SUCCESSFUL
OBJECTS: 1 TOTAL
    OBJECT ID                             SHAPE             COLORS  HELD   POSITION (WORLD)                    DIMENSIONS (WORLD)  DISTANCE (WORLD)  DIRECTION (WORLD)                   
    f5487b06-7a01-45d8-bbda-2cf893b7d126  blank block cube  yellow  False  (4.199999,0.100000121,-4.35999966)  None                2.7885952         (0.16351971,-0.130688861,-0.9778455)
===============================================================================
All actions available during this step.
Enter your command:

You entered command:
MoveAhead
===============================================================================
STEP: 6
ACTION: MoveAhead
wRETURN STATUS: SUCCESSFUL
OBJECTS: 1 TOTAL
    OBJECT ID                             SHAPE             COLORS  HELD   POSITION (WORLD)                    DIMENSIONS (WORLD)  DISTANCE (WORLD)  DIRECTION (WORLD)                      
    f5487b06-7a01-45d8-bbda-2cf893b7d126  blank block cube  yellow  False  (4.199999,0.100000121,-4.35999966)  None                2.54240561        (0.164067835,-0.143500209,-0.975955665)
===============================================================================
All actions available during this step.
Enter your command:

You entered command:
MoveAhead
===============================================================================
STEP: 7
ACTION: MoveAhead
wRETURN STATUS: SUCCESSFUL
OBJECTS: 1 TOTAL
    OBJECT ID                             SHAPE             COLORS  HELD   POSITION (WORLD)                    DIMENSIONS (WORLD)  DISTANCE (WORLD)  DIRECTION (WORLD)                    
    f5487b06-7a01-45d8-bbda-2cf893b7d126  blank block cube  yellow  False  (4.199999,0.100000121,-4.35999966)  None                2.29703951        (0.164697737,-0.159060225,-0.9734344)
===============================================================================
All actions available during this step.
Enter your command:

You entered command:
MoveAhead
===============================================================================
STEP: 8
ACTION: MoveAhead
RETURN STATUS: SUCCESSFUL
OBJECTS: 1 TOTAL
    OBJECT ID                             SHAPE             COLORS  HELD   POSITION (WORLD)                    DIMENSIONS (WORLD)  DISTANCE (WORLD)  DIRECTION (WORLD)                      
    f5487b06-7a01-45d8-bbda-2cf893b7d126  blank block cube  yellow  False  (4.199999,0.100000121,-4.35999966)  None                2.052792          (0.165423468,-0.178343177,-0.969963253)
===============================================================================
All actions available during this step.
Enter your command:
w, amount=0.38 
You entered command:
MoveAhead  amount=0.38
===============================================================================
STEP: 9
ACTION: MoveAhead
RETURN STATUS: SUCCESSFUL
OBJECTS: 1 TOTAL
    OBJECT ID                             SHAPE             COLORS  HELD   POSITION (WORLD)                    DIMENSIONS (WORLD)  DISTANCE (WORLD)  DIRECTION (WORLD)                    
    f5487b06-7a01-45d8-bbda-2cf893b7d126  blank block cube  yellow  False  (4.199999,0.100000121,-4.35999966)  None                1.86818206        (0.1660466,-0.196373761,-0.966367364)
===============================================================================
All actions available during this step.
Enter your command:
PickupObject, objectId=f5487b06-7a01-45d8-bbda-2cf893b7d126
You entered command:
PickupObject  objectId=f5487b06-7a01-45d8-bbda-2cf893b7d126
===============================================================================
STEP: 10
ACTION: PickupObject
RETURN STATUS: OUT_OF_REACH
OBJECTS: 1 TOTAL
    OBJECT ID                             SHAPE             COLORS  HELD   POSITION (WORLD)                    DIMENSIONS (WORLD)  DISTANCE (WORLD)  DIRECTION (WORLD)                    
    f5487b06-7a01-45d8-bbda-2cf893b7d126  blank block cube  yellow  False  (4.199999,0.100000121,-4.35999966)  None                1.86818206        (0.1660466,-0.196373761,-0.966367364)
===============================================================================
All actions available during this step.
Enter your command:
`

**Comment by deanwetherby** [comment]
I notice that the distance is reducing by ~0.25 rather than 0.5 as we would expect. I'm curious if the script MoveAhead default value of 0.5 is not correct. I ran again but provided an amount of 1.0 for the action and noticed that the distance dropped by nearly 0.5. Something's off between these values and the optimal path steps.

'''
All actions available during this step.
Enter your command:
r, rotation=81
You entered command:
RotateLook  rotation=81
===============================================================================
STEP: 1
ACTION: RotateLook
RETURN STATUS: SUCCESSFUL
OBJECTS: 1 TOTAL
    OBJECT ID                             SHAPE             COLORS  HELD   POSITION (WORLD)                    DIMENSIONS (WORLD)  DISTANCE (WORLD)  DIRECTION (WORLD)                    
    f5487b06-7a01-45d8-bbda-2cf893b7d126  blank block cube  yellow  False  (4.199999,0.100000121,-4.35999966)  None                3.77836037        (0.161913961,-0.0962195,-0.982102633)
===============================================================================
All actions available during this step.
Enter your command:
w, amount=1.0
You entered command:
MoveAhead  amount=1.0
===============================================================================
STEP: 2
ACTION: MoveAhead
RETURN STATUS: SUCCESSFUL
OBJECTS: 1 TOTAL
    OBJECT ID                             SHAPE             COLORS  HELD   POSITION (WORLD)                    DIMENSIONS (WORLD)  DISTANCE (WORLD)  DIRECTION (WORLD)                      
    f5487b06-7a01-45d8-bbda-2cf893b7d126  blank block cube  yellow  False  (4.199999,0.100000113,-4.35999966)  None                3.28270221        (0.162618816,-0.110852458,-0.980442166)
===============================================================================
All actions available during this step.
Enter your command:
'''

**Comment by deanwetherby** [comment]
I got to the bottom of the move distance confusion. The default move action in the run script uses amount=0.5. Amount is multiplied by the maximum move distance which is also 0.5. So the default move action magnitude is obviously 0.5*0.5=0.25. By providing the non-default maximum move amount of 1.0, the move magnitude is the expected 0.5. Seeing how this is an optimal path finder, this move magnitude of maximum is appropriate although I do find the multiplicative nature of this logic a little confusing from the controller side of things. Why not provide an amount up to the maximum move distance of 0.5 rather than multiplying? Why isn't the default the maximum? Oh well.

Using my 'bob' example scene from before, the initial rotation is correct but I'm noticing that there are some unnecessary extra steps taken in this segment. After taking the sixth step forward with amount=1.0, I noticed that the goal object distance was 0.88 which is within the agent's maximum reach of 1.0. There's no need to take the next full or the following partial step (0.38) or even the horizon rotation. The agent can simply pick up the object from there while it's in view. 

```
All actions available during this step.
Enter your command:
w, amount=1.0
You entered command:
MoveAhead  amount=1.0
===============================================================================
STEP: 7
ACTION: MoveAhead
RETURN STATUS: SUCCESSFUL
OBJECTS: 1 TOTAL
    OBJECT ID                             SHAPE             COLORS  HELD   POSITION (WORLD)                    DIMENSIONS (WORLD)  DISTANCE (WORLD)  DIRECTION (WORLD)                      
    f5487b06-7a01-45d8-bbda-2cf893b7d126  blank block cube  yellow  False  (4.199999,0.100000121,-4.35999966)  None                0.881348          (0.168855473,-0.435053438,-0.884429932)
===============================================================================
```

**Comment by ThomasSchellenbergNextCentury** [comment]
@deanwetherby Just popping in to answer a few questions:

> Why not provide an amount up to the maximum move distance of 0.5 rather than multiplying? Why isn't the default the maximum?

My original assumption was that the maximum move distance may change depending on your current pose (lying down and rolling vs. on hands/knees and crawling vs. standing and walking), or if we wanted to simulate babies of different ages (6 months vs. 12 months vs. 18 months) depending on the test.  So a percentage made more sense to handle those use cases, but, like everything, we can certainly change how it works if that makes more sense moving forward.

**Comment by ThomasSchellenbergNextCentury** [comment]
@chrislong I agree with Dean that each `MoveAhead` action should have an `amount=1` parameter.  Even the last `MoveAhead` action could probably(?) move the full amount as well, if calculating the precise amount to use is particularly hard.  I think this was part of the original ticket's description (from three months ago), but probably got forgotten among all of the other requirements.

**Comment by deanwetherby** [comment]
@ThomasSchellenbergNextCentury For one mode, the amount is confusing but I see what you mean for multiple modes of movement. Maximum crawling effort still isn't as fast as running. 

> My original assumption was that the maximum move distance may change depending on your current pose (lying down and rolling vs. on hands/knees and crawling vs. standing and walking), or if we wanted to simulate babies of different ages (6 months vs. 12 months vs. 18 months) depending on the test. So a percentage made more sense to handle those use cases, but, like everything, we can certainly change how it works if that makes more sense moving forward.

**Comment by chrislong** [comment]
@deanwetherby Thanks for tracking down that movement weirdness! I agree the action list could be shorted by avoiding the last step or couple of steps to the target. Right now the code doesn't account for reach distance, which it could. I'd really like that to be another ticket, though.

@ThomasSchellenbergNextCentury I'll change the code to include `amount=1` in the `params` instead of relying on a default. (I'll push it to this branch today.)

**Comment by deanwetherby** [comment]
@chrislong Agree concerning another ticket. MCS-285 is the new one accounting for agent reach in path planning.

**Comment by deanwetherby** [comment]
Everything worked fine up until the last PutObject on a newly generated scene. There's no horizon rotation so the target2 base goal object is not in view and the action fails with 'out of reach'. The amount=1.0 were in the generated file so good there.

image

```
STEP: 14
ACTION: MoveAhead
RETURN STATUS: SUCCESSFUL
OBJECTS: 1 TOTAL
    OBJECT ID                             SHAPE              COLORS       HELD  POSITION (WORLD)                  DIMENSIONS (WORLD)  DISTANCE (WORLD)  DIRECTION (WORLD)                     
    621f63ff-e7fa-44e3-8674-f456c7b9c73f  letter block cube  blue, brown  True  (3.2136085,0.3409891,-3.7314136)  None                0.238606557       (0.57133913,-0.623658836,-0.533498943)
===============================================================================
All actions available during this step.
Enter your command:
PutObject, objectId=621f63ff-e7fa-44e3-8674-f456c7b9c73f, receptacleObjectId=8720a109-e744-4f11-b8dc-f9134aee935b
You entered command:
PutObject  objectId=621f63ff-e7fa-44e3-8674-f456c7b9c73f  receptacleObjectId=8720a109-e744-4f11-b8dc-f9134aee935b
===============================================================================
STEP: 15
ACTION: PutObject
RETURN STATUS: OUT_OF_REACH
```

**Comment by chrislong** [comment]
Just to make sure I understand: the problem is that the agent needs to look down before trying PutObject?

**Comment by deanwetherby** [comment]
Yes. Exactly like the action on the first object. The base or target 2 object has to be within the field of view for the put action to work.

**Comment by chrislong** [comment]
Ok. Thanks for all the testing. I'll fix it tomorrow.

**Comment by deanwetherby** [comment]
In all fairness, another goal answer had the horizon rotation right before the PutObject.

```
      {
        "action": "RotateLook",
        "params": {
          "rotation": 0.0,
          "horizon": 82.43
        }
      },
      {
        "action": "PutObject",
        "params": {
          "objectId": "6724f30d-e041-401f-81ab-1ae54566307c",
          "receptacleObjectId": "41faeeea-1430-46b8-a148-b71b55afcf67"
        }
      }
```

**Comment by chrislong** [comment]
Yeah, it checked whether it needed to look down before picking something up, but not before putting it down. I guess it assumed the receptacle was tall enough. Anyway, it now checks and should look down at a receptacle if necessary before doing the PutObject action.

**Comment by ThomasSchellenbergNextCentury** [comment]
@deanwetherby Is this good now?

**Comment by deanwetherby** [comment]
Thanks for the reminder. I'll test a couple of scenes and post back here with the results.

**Comment by deanwetherby** [comment]
Had an issue with one so far. The answer had the agent rotate and move in the beginning but the object was right in front of the agent. I'm not sure at what point we close this ticket and make new ones though. I just want to ensure this capability is as close to solid as we can get it. Curious what you think @ThomasSchellenbergNextCentury @chrislong on that topic.

Here's the view on the first step when I just rotated the horizon down a bit.
image

[transferral-0001.json.txt](https://github.com/NextCenturyCorporation/MCS/files/4838036/transferral-0001.json.txt)

**Comment by ThomasSchellenbergNextCentury** [comment]
@deanwetherby So is the issue in the attached ticket that there's an extra RotateLook (rotation=262) at the start of the action list?

I'm fine with starting some new tickets, unless @chrislong knows a quick fix for this specific issue.

**Comment by chrislong** [comment]
I'd vote for making another ticket.

**Pull request merged**
