### PR TITLE
Mcs 95 config room size

### PR DESCRIPTION
**Pull request by kdrumm**
Integration tests and documentation for MCS-95 which adds configuration to change the room size.

See https://github.com/NextCenturyCorporation/ai2thor/pull/118 which should be merged before this.

### CODE REVIEW

**Comment by ThomasSchellenbergNextCentury** [comment]
@brianpippin I think you missed my status as standup this morning that some of the integration tests were broken. (They're all fixed now, and merged into development, but I haven't gotten to merge them into Kyle's feature branches yet! Always a step behind...)

**Comment by ThomasSchellenbergNextCentury** [comment]
@brianpippin @kdrumm I merged development into this branch. All of the integration tests should work now! Thanks for your patience.

**Review by ThomasSchellenbergNextCentury — APPROVED** [review]
Looks great. A couple of comments:
- The example scenes you have here are good, so no changes needed, but be aware that any scenes posted to this repo will be very visible to TA1, so just be mindful about what you commit.
- Please let me know if you have any feedback about the process of making new integration tests -- you're the first one (besides me) to do so!

**Comment by kdrumm** [comment]
Will merge once corresponding AI2Thor pull request gets re-approved

**Comment by kdrumm** [comment]
Added a note about maximum visibility distance to documentation.

**Pull request merged**
