### PR TITLE
MCS-1567 Updated integration tests due to prefab changes in the container with the separate lid.

### PR DESCRIPTION
**Pull request by ThomasSchellenbergNextCentury**
Unity PR: https://github.com/NextCenturyCorporation/ai2thor/pull/292
ILE PR: https://github.com/NextCenturyCorporation/mcs-private/pull/322

### CODE REVIEW

**Comment by brianpippin** [comment]
I've run this three times now and I can't get the tests to pass.  I built the MCS-1567 AI2Thor branch, with the assets copied from the MCS-1567 branch in mcs-private, however, tests 154, 158, and 170 fail for me.  Am I missing a step to get this to work?

**Comment by ThomasSchellenbergNextCentury** [comment]
@brianpippin I'm sorry to hear you've encountered some trouble! It sounds like you've done everything correctly, but obviously something fishy is still happening. 170 was directly changed in this PR, and 154 and 158 were also affected by the Unity PR, but I just double checked and all of the commits I made had already been pushed up... Hmm. I will try rebuilding addressables and rerunning everything, and I'll get back to you on Monday. In the meantime, these are the steps I usually take, if you want to compare them to your own process.

1. In `mcs-private`, checkout the correct feature branch and pull the latest
2. Copy files from `<mcs-private>/UnityAssetStore/Custom/*` into `<ai2thor>/unity/Assets/Addressables/MCS/UnityAssetStore/Custom/`
3. In `ai2thor`, checkout the correct feature branch and pull the latest
4. Delete the `<ai2thor>/unity/ServerData/` folder
5. In the Unity Editor, first click `Window->Asset Management->Addressables->Groups`, then `Build->Clean Build->All`, and finally `Build->New Build->Default Build Script`
6. Build the Unity executable
7. Delete my locally cached addressables: `rm -rf /tmp/CACI\ with\ the\ Allen\ Institute\ for\ Artificial\ Intelligence_MCS-AI2-THOR/`
8. In the new ServerData/ folder, run `sudo python3 -m http.server 80`
9. In `mcs`, checkout the correct feature branch and pull the latest
10. Run: `source venv/bin/activate`
11. Spot check relevant integration tests: `python integration_tests/run_tests.py --mcs_unity_build <mcs-unity-exe> --test <whatever> --dev`
12. Do a full integration test run

**Comment by ThomasSchellenbergNextCentury** [comment]
@brianpippin I did find an issue with test 174 that I had forgotten to fix (just pushed a commit), but all the other tests worked for me.

**Comment by ThomasSchellenbergNextCentury** [comment]
The fact that you're seeing issues with tests 154, 158, and 170, but NOT with other tests like 174, makes me think that the issue lies in the addressables build (something's different on one of our two machines). Hopefully Rachel/Jacob can provide some more insight.

**Comment by rartiss55** [comment]
@ThomasSchellenbergNextCentury @brianpippin I tried this following the instructions above. So far I only ran the problematic tests in isolation (154, 158, 170, 174), and they all passed. I will run the full test suite now. 

For Brian's issue, when I copied the assets over from the mcs-private branch, I usually pick the merge option when prompted on the Mac instead of a full copy so it will just add the newest items. However, doing a merge this time was problematic, since this time files were deleted from the mcs-private assets, and they didn't get deleted properly for me the first time I had tried. So perhaps some of the issues step from there. Might be worth deleting the <ai2thor>/unity/Assets/Addressables/MCS/UnityAssetStore/Custom/ folder
before readding it, or just deleting those 4 assets.

**Comment by jaudick** [comment]
@ThomasSchellenbergNextCentury @brianpippin @rartiss55  I also got no failures running all of the tests

**Review by brianpippin — APPROVED** [review]

**Comment by ThomasSchellenbergNextCentury** [comment]
I'm glad we're all on the same page regarding testing. Unfortunately on that front, Jacob made a good suggestion (which I agree with) about making sure the height of the lid was scaled correctly... which meant I needed to make a minor change to the assets and tests. Maybe we can just make one person (Jacob?) run the tests this time, to avoid burdening the whole team again? Sorry for the headache.

**Pull request merged**
